authenticationCachePolicy: maximumSize=10000, expireAfterAccess=10m

federatedAuthentication:
  credentials: Huygens security-server-key-here
  url: security-server-url-here

google:
  clientId: your-client-id-here.apps.googleusercontent.com
  clientSecret: your-client-secret-here

jerseyClient:
  timeout: 10s

localAddresses:
  - "localhost"
  - "127.0.0.1"
  - "0:0:0:0:0:0:0:1"

logging:
  level: INFO
  appenders:
    - type: console

  loggers:
    nl.knaw.huc.di.sesame: DEBUG
    nl.knaw.huc.di.sesame.resources: TRACE
